[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./script" }]
solc_version = "0.8.26"
optimizer = true
optimizer_runs = 200
# via_ir = true required for MultiLPSimulation.s.sol (stack too deep)
via_ir = true
evm_version = "cancun"

remappings = [
    "forge-std/=lib/forge-std/src/",
    "@uniswap/v4-core/=lib/v4-core/",
    "@uniswap/v4-periphery/=lib/v4-periphery/"
]

[profile.ci]
optimizer_runs = 200
fuzz_runs = 1000
